# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-Loader-Relationship
version:      1.3
version_from: Relationship.pm
installdirs:  site
requires:
    Class::DBI::Loader:            0
    Lingua::EN::Inflect::Number:   1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
